# Generated by Django 3.0.7 on 2020-08-31 07:17

import blog.models
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
                ('slug', models.SlugField(default='default', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновленния')),
                ('image', models.ImageField(blank=True, null=True, upload_to=blog.models.image_dir, verbose_name='Главное фото')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контент')),
                ('excert', models.TextField(blank=True, max_length=200, null=True, verbose_name='Краткое описание')),
                ('slug', models.SlugField(blank=True, max_length=150, null=True, unique=True)),
                ('status', models.BooleanField(default=True, verbose_name='Опубликовать?')),
                ('comment_status', models.BooleanField(default=True, verbose_name='Можно комментировать?')),
                ('category', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='blog.Category', verbose_name='Категория')),
            ],
            options={
                'ordering': ['-post_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Post_Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=blog.models.gallery_dir)),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
            ],
        ),
    ]
