# Generated by Django 3.0.7 on 2020-09-12 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_inline_editor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inline_editor',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='post_gallery',
            options={'ordering': ['id']},
        ),
    ]
