# Generated by Django 3.0.7 on 2020-10-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200915_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
