# Generated by Django 3.0.7 on 2020-10-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_my_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['my_order']},
        ),
        migrations.AlterField(
            model_name='post',
            name='my_order',
            field=models.IntegerField(default=0),
        ),
    ]
