# Generated by Django 3.0.7 on 2020-10-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20201017_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='my_order',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
    ]
