# Generated by Django 3.0.7 on 2020-10-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20201017_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
