# Generated by Django 3.0.7 on 2020-10-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_menu', '0002_menu_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='slug',
            field=models.CharField(default=1, max_length=200, verbose_name='Сылка'),
            preserve_default=False,
        ),
    ]
